
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[234] =
    {   0,
        0,    0,    0,    0,    0,    0,   58,   56,   53,   54,
       55,   50,   56,   39,   40,   36,   34,   41,   35,   56,
       37,   26,   26,   45,   42,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   43,   44,   56,
       56,   47,   49,   47,   52,   51,   52,    0,    0,   38,
       27,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       27,    0,    0,   46,    0,    0,    0,    0,    0,   26,
       25,   25,    0,   25,   25,   25,   25,   20,    0,   25,
       25,   25,   25,   25,   16,   25,   25,   25,   25,   25,
       25,   25,   25,    0,   27,   49,   48,   49,   51,   29,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   27,    0,    0,   26,   26,    0,    0,   26,
       27,    0,   26,   27,   27,   27,   25,   25,   25,    0,
       25,   25,   25,   25,   25,   25,    3,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,    0,    0,
        0,   33,    0,    0,   30,    0,   27,   26,   26,   27,
       26,   27,   26,   27,    0,   25,   13,   25,   25,   25,
       25,   10,   18,   25,   25,   25,   12,   25,   25,   25,
       14,    6,   25,   22,   25,   17,   25,    0,    0,   31,
        0,   32,    0,   25,   25,   25,   25,   21,   19,   25,

       25,   25,   25,   25,   25,   15,    0,   28,   25,    4,
       25,   25,   25,   25,   24,   25,   23,   25,   25,    7,
       25,   25,    5,    8,   25,   25,   11,    1,   25,    9,
       25,    2,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    6,    6,    7,    6,    6,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,    6,    6,
       22,    6,    6,    6,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   32,   32,
       46,   47,   48,    6,   49,    6,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   32,   32,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   43,   69,   70,
       32,   32,    6,    6,    6,    6,    1,    1,    1,    1,
        1,    1,    1,    1,   71,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   72,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   73,    1,
        1,    1,    1,    1,    1,    1,   71,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       72,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       73,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,   74,   71,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    3,    2,    2,
        2,    2,    2,    2,    4,    2,    5,    5,    5,    5,
        2,    2,    6,    7,    6,    6,    6,    7,    8,    8,
        8,    8,    8,    8,    9,    8,    8,    8,    9,    8,
        9,    8,    9,    8,    8,    2,    2,    2,   10,    6,
        7,    6,    6,    6,    7,    8,    8,    8,    8,    8,
        9,    8,    8,    8,    9,    8,    9,    8,    8,    8,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[250] =
    {   0,
        0,    0,   72,   73,   74,   76,  317, 1552, 1552, 1552,
     1552, 1552,  267, 1552, 1552,  296, 1552, 1552, 1552,  104,
     1552,  164,   72, 1552, 1552,   64,  193,  105,  213,  131,
      221,  241,  243,   76,  267,  265,  293, 1552, 1552,    0,
       92, 1552, 1552,   82, 1552, 1552,  303,  296,  295, 1552,
      301,   53,  319,   84,  120,  187,  141,   77,   78,  329,
      187,  344,  350, 1552,  335,   83,  284,  361,  370,  376,
      390,  394,    0,  402,  406,  440,  427,  446,  306,  453,
      463,  467,  479,  489,  504,  514,  524,  528,  547,  572,
      581,  592,  598,  605,  532, 1552, 1552,  295, 1552, 1552,

      269,  143,  253,  105,  241,  238,  237,  232,  230,  131,
      193,  133,  618,  135,  175,  202,  139,  246,  419,  473,
        0,  187,  174,  263,  210,  625,  631,  640,    0,   87,
      644,  648,  665,  655,  688,  699,  713,  732,  723,  750,
      769,  774,  789,  794,  809,  832,  847,  836,  856,  869,
      103, 1552,  209,  100, 1552,  143,  168,  274,  222,  423,
      500,    0,   93,  435,   56, 1552,  873,  881,  892,  896,
      907,  915,  929,  933,  942,  955,  966,  970,  983,  988,
      992, 1010, 1016, 1025, 1034, 1029, 1044, 1067, 1071, 1552,
      240, 1552,   86, 1082, 1086, 1091, 1095, 1105, 1109, 1119,

     1142, 1146, 1155, 1162, 1166, 1170,   82, 1552, 1181, 1207,
     1218, 1222, 1232, 1226, 1240, 1259, 1265, 1278, 1282, 1286,
     1293, 1304, 1331, 1337, 1341, 1349, 1356, 1364, 1374, 1383,
     1398, 1402, 1552, 1452, 1462, 1471, 1477, 1482, 1491, 1499,
     1505, 1509, 1512, 1517, 1522, 1528, 1532, 1535, 1541
    } ;

static const flex_int16_t yy_def[250] =
    {   0,
      233,    1,  234,  234,  235,  235,  233,  233,  233,  233,
      233,  233,  236,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  237,  237,   27,  237,  237,
       27,  237,   27,  237,  237,   27,  237,  233,  233,  238,
      233,  233,  233,  239,  233,  233,  233,  233,  240,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  241,  242,  233,  242,  233,
      237,  243,  244,  243,  243,  243,  243,  243,  233,  237,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  245,  233,  233,  233,  233,  233,  233,

      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      246,  242,  247,  246,   69,  242,  243,  243,  244,  248,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  245,  249,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  246,  247,  246,  248,  233,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  249,  249,  233,
      233,  233,  233,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  233,  233,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,    0,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233
    } ;

static const flex_int16_t yy_nxt[1627] =
    {   0,
        8,    9,   10,   11,    9,    8,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   23,   23,
       24,   25,   26,   26,   27,   28,   29,   30,   31,   26,
       32,   26,   33,   26,   26,   26,   26,   26,   34,   35,
       36,   26,   26,   37,   26,   38,    8,   39,   40,   26,
       26,   27,   28,   29,   30,   31,   26,   32,   33,   26,
       26,   26,   26,   26,   34,   35,   36,   26,   37,   26,
        8,   41,    8,   41,   43,   43,   46,   47,   46,   47,
       71,   71,   71,   71,   97,   98,   61,  102,   70,   70,
       70,   70,   71,   71,   71,   71,  208,  121,   60,  122,

      208,   64,   89,   79,  166,   79,  104,  121,   95,   95,
       95,   95,   73,  102,  192,  111,  112,  190,   44,   44,
       51,   51,   51,   51,   73,   60,   52,   77,   64,   89,
       53,   54,   55,  104,   72,  166,   56,  153,   57,   58,
       78,  111,  112,   60,   59,   60,  105,   71,   71,   71,
       71,  157,  157,   52,   77,  159,  159,   53,   54,   55,
      106,   72,   56,  153,   57,   58,   78,  109,  151,  193,
       59,  154,   83,  105,  156,   60,  110,   60,   61,   73,
       62,   62,   62,   62,  157,  157,  106,   63,  121,  114,
       60,  115,  115,   64,  109,  151,  193,  154,   83,   65,

      156,  121,  110,  113,  113,  113,  113,  155,   66,   71,
       71,   71,   71,  107,   63,   74,  114,   60,  158,  158,
       64,  233,   75,  233,   79,   65,   79,  108,   76,   80,
       80,   80,   80,   66,   67,   60,   68,   69,  159,  159,
      107,   73,   74,   72,  152,   81,  152,   82,  191,   75,
       72,  152,  152,  108,   76,  152,   84,   71,   71,   71,
       71,   73,  160,  160,  160,   72,  207,  152,   85,   87,
       72,   81,   72,   82,  191,   86,  100,   72,   88,  164,
      164,  164,   84,   71,   71,   71,   71,   72,  114,   73,
      158,  158,   72,  207,   92,   85,   87,   97,  121,   72,

       72,   86,  100,  100,   88,   99,   50,   90,   91,   71,
       71,   71,   71,   49,   72,   73,  233,   51,   51,   51,
       51,   92,   95,   95,   95,   95,   72,   60,  233,  233,
       79,   93,   79,   90,   91,   95,   95,   95,   95,  233,
       79,   73,   79,  233,  233,   95,   95,   95,   95,  118,
      233,  119,  120,  120,   60,  233,  103,   93,   61,  233,
       62,   62,   62,   62,  114,  233,  115,  116,  117,  117,
       60,  233,   60,   64,   60,  118,  233,  119,  119,  119,
      233,   79,  103,   79,  124,  233,  125,  125,  125,  126,
       61,  233,   70,   70,   70,   70,  233,   60,  233,  233,

       64,  233,   60,  233,  233,   64,   71,   71,   71,   71,
      127,  127,  127,  127,  233,   60,  233,   60,  127,  127,
      127,  127,  127,  127,  127,  127,  233,  233,  132,   60,
      233,  233,   64,  118,  131,  119,  119,  119,   73,  160,
      160,  160,  129,  127,  127,  127,  127,   60,  233,   60,
      129,  164,  164,  164,  129,  132,  127,  127,  127,  127,
      131,  233,  127,  127,  127,  127,  233,  135,  233,   80,
       80,   80,   80,  133,  134,  129,  233,  233,  233,  127,
      127,  127,  127,  127,  127,  127,  127,  118,  129,  161,
      161,  161,  137,  135,  129,  127,  127,  127,  127,  133,

      134,   73,  136,  233,  233,  127,  127,  127,  127,  233,
      233,  129,  233,  138,  118,  129,  161,  161,  161,  137,
      127,  127,  127,  127,  233,  233,  233,  129,  136,  139,
      127,  127,  127,  127,  233,  233,  233,  129,  233,  138,
      127,  127,  127,  127,  127,  127,  127,  127,   95,   95,
       95,   95,  129,  233,  140,  139,  142,  233,  141,  233,
      233,  233,  129,  127,  127,  127,  127,  233,  233,  143,
      233,  233,  129,  233,  233,  233,  129,  233,  233,  233,
      140,  233,  233,  142,  141,  233,  233,  144,  127,  127,
      127,  127,  233,  233,  233,  129,  143,  127,  127,  127,

      127,  233,  233,  233,  146,  233,  233,  145,  127,  127,
      127,  127,  233,  144,  127,  127,  127,  127,  147,  233,
      129,  149,  149,  149,  149,  233,  233,  233,  148,  129,
      233,  146,  233,  145,  113,  113,  113,  113,  233,  121,
      129,  126,  126,  126,  126,  147,  129,  127,  127,  127,
      127,  233,  233,   73,  233,  148,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  233,  233,
      233,  127,  127,  127,  127,  233,  167,  233,  233,  129,
      233,  127,  127,  127,  127,  233,  168,  233,  129,  233,
      233,  233,  129,  233,  233,  171,  129,  233,  169,  233,

      233,  170,  167,  129,  127,  127,  127,  127,  233,  233,
      172,  233,  168,  129,  233,  127,  127,  127,  127,  233,
      233,  171,  233,  233,  169,  173,  233,  170,  233,  127,
      127,  127,  127,  233,  233,  233,  129,  172,  174,  127,
      127,  127,  127,  175,  233,  233,  233,  129,  127,  127,
      127,  127,  173,  233,  233,  233,  176,  233,  177,  233,
      233,  129,  233,  233,  233,  174,  127,  127,  127,  127,
      175,  129,  233,  233,  233,  233,  178,  233,  233,  233,
      129,  233,  233,  176,  177,  127,  127,  127,  127,  233,
      127,  127,  127,  127,  233,  233,  233,  179,  129,  233,

      233,  233,  233,  178,  180,  127,  127,  127,  127,  233,
      127,  127,  127,  127,  181,  233,  233,  129,  233,  233,
      233,  182,  129,  233,  179,  127,  127,  127,  127,  233,
      233,  180,  233,  233,  233,  183,  233,  129,  233,  233,
      233,  181,  129,  233,  233,  184,  233,  182,  127,  127,
      127,  127,  127,  127,  127,  127,  233,  129,  233,  233,
      233,  183,  233,  127,  127,  127,  127,  233,  233,  233,
      185,  184,  149,  149,  149,  149,  187,  233,  233,  233,
      129,  186,  233,  233,  129,  188,  188,  188,  188,  127,
      127,  127,  127,  233,  233,  129,  185,  127,  127,  127,

      127,  233,  187,  194,   73,  233,  233,  186,  127,  127,
      127,  127,  127,  127,  127,  127,  233,  129,  233,  233,
      233,  129,  233,  127,  127,  127,  127,  195,  196,  129,
      194,  127,  127,  127,  127,  233,  233,  197,  233,  233,
      129,  233,  233,  233,  129,  127,  127,  127,  127,  127,
      127,  127,  127,  195,  196,  129,  233,  233,  127,  127,
      127,  127,  233,  129,  197,  233,  233,  233,  198,  199,
      233,  127,  127,  127,  127,  233,  233,  129,  233,  233,
      233,  129,  127,  127,  127,  127,  127,  127,  127,  127,
      129,  233,  233,  233,  198,  200,  199,  233,  201,  127,

      127,  127,  127,  129,  127,  127,  127,  127,  127,  127,
      127,  127,  203,  233,  129,  233,  233,  233,  129,  233,
      233,  200,  233,  202,  233,  201,  127,  127,  127,  127,
      233,  129,  127,  127,  127,  127,  129,  233,  233,  203,
      129,  127,  127,  127,  127,  127,  127,  127,  127,  202,
      127,  127,  127,  127,  204,  233,  233,  233,  129,  233,
      127,  127,  127,  127,  129,  233,  233,  233,  233,  205,
      206,  233,  233,  129,  233,  233,  233,  129,  233,  233,
      204,  233,  129,  188,  188,  188,  188,  188,  188,  188,
      188,  233,  129,  233,  233,  205,  233,  206,  127,  127,

      127,  127,  127,  127,  127,  127,  209,  127,  127,  127,
      127,  127,  127,  127,  127,  129,  233,  211,  233,  129,
      210,  127,  127,  127,  127,  127,  127,  127,  127,  212,
      129,  233,  233,  209,  129,  127,  127,  127,  127,  129,
      233,  233,  233,  129,  211,  233,  210,  233,  233,  213,
      233,  233,  233,  129,  233,  212,  233,  129,  127,  127,
      127,  127,  127,  127,  127,  127,  233,  129,  214,  233,
      233,  127,  127,  127,  127,  215,  213,  216,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      129,  233,  233,  233,  129,  214,  217,  127,  127,  127,

      127,  233,  215,  129,  216,  233,  233,  218,  233,  233,
      129,  233,  233,  233,  129,  233,  233,  233,  129,  233,
      233,  219,  217,  127,  127,  127,  127,  233,  233,  129,
      233,  233,  233,  218,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  233,  219,  127,  127,
      127,  127,  233,  233,  233,  129,  127,  127,  127,  127,
      233,  233,  220,  221,  223,  233,  129,  222,  233,  233,
      129,  233,  233,  233,  129,  127,  127,  127,  127,  233,
      129,  127,  127,  127,  127,  233,  233,  220,  129,  221,
      223,  224,  233,  222,  127,  127,  127,  127,  127,  127,

      127,  127,  127,  127,  127,  127,  233,  129,  226,  127,
      127,  127,  127,  129,  233,  233,  233,  224,  225,  227,
      127,  127,  127,  127,  233,  233,  129,  233,  233,  233,
      129,  233,  233,  233,  129,  226,  233,  233,  228,  233,
      233,  129,  233,  233,  225,  233,  227,  127,  127,  127,
      127,  233,  129,  127,  127,  127,  127,  127,  127,  127,
      127,  233,  233,  233,  228,  127,  127,  127,  127,  233,
      233,  229,  127,  127,  127,  127,  233,  233,  233,  129,
      127,  127,  127,  127,  233,  129,  233,  230,  233,  129,
      127,  127,  127,  127,  233,  233,  233,  129,  229,  127,

      127,  127,  127,  233,  129,  233,  233,  233,  231,  233,
      233,  233,  129,  230,  127,  127,  127,  127,  127,  127,
      127,  127,  129,  233,  232,  233,  233,  233,  233,  233,
      233,  129,  233,  233,  231,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  129,  233,  233,  233,
      129,  232,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   72,   72,   72,   72,   72,   72,   94,   94,   94,
       94,   96,   96,   96,   96,   96,   96,   96,   96,   96,

       96,  101,  233,  233,  233,  101,  233,  101,  123,  123,
      123,  123,  122,  122,  122,  122,  128,  128,  128,  128,
      128,  128,  130,  130,  130,  130,  150,  150,  150,  150,
      150,  150,  162,  162,  162,  163,  163,  163,  163,  165,
      165,  165,  165,  165,  165,  189,  189,  189,  189,  189,
      189,    7,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,

      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233
    } ;

static const flex_int16_t yy_chk[1627] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    5,    6,    6,
       26,   26,   26,   26,   44,   44,   23,   52,   23,   23,
       23,   23,   34,   34,   34,   34,  207,   66,   23,   66,

      193,   23,   34,   41,  165,   41,   54,  163,   41,   41,
       41,   41,   26,   52,  154,   58,   59,  151,    3,    4,
       20,   20,   20,   20,   34,   23,   20,   28,   23,   34,
       20,   20,   20,   54,   28,  130,   20,  104,   20,   20,
       28,   58,   59,   23,   20,   23,   55,   30,   30,   30,
       30,  114,  114,   20,   28,  117,  117,   20,   20,   20,
       55,   28,   20,  104,   20,   20,   28,   57,  102,  156,
       20,  110,   30,   55,  112,   20,   57,   20,   22,   30,
       22,   22,   22,   22,  157,  157,   55,   22,  123,  115,
       22,  115,  115,   22,   57,  102,  156,  110,   30,   22,

      112,  122,   57,   61,   61,   61,   61,  111,   22,   27,
       27,   27,   27,   56,   22,   27,  116,   22,  116,  116,
       22,  125,   27,  125,   29,   22,   29,   56,   27,   29,
       29,   29,   29,   22,   22,   22,   22,   22,  159,  159,
       56,   27,   27,   31,  109,   29,  108,   29,  153,   27,
       31,  107,  106,   56,   27,  105,   31,   32,   32,   32,
       32,   29,  118,  118,  118,   33,  191,  103,   32,   33,
       31,   29,   33,   29,  153,   32,  101,   31,   33,  124,
      124,  124,   31,   35,   35,   35,   35,   36,  158,   32,
      158,  158,   33,  191,   36,   32,   33,   98,   67,   33,

       36,   32,   49,   48,   33,   47,   16,   35,   35,   37,
       37,   37,   37,   13,   36,   35,    7,   51,   51,   51,
       51,   36,   79,   79,   79,   79,   36,   51,    0,    0,
       53,   37,   53,   35,   35,   53,   53,   53,   53,    0,
       60,   37,   60,    0,    0,   60,   60,   60,   60,   65,
        0,   65,   65,   65,   51,    0,   53,   37,   62,    0,
       62,   62,   62,   62,   63,    0,   63,   63,   63,   63,
       62,    0,   51,   62,   51,   68,    0,   68,   68,   68,
        0,   69,   53,   69,   69,    0,   69,   69,   69,   69,
       70,    0,   70,   70,   70,   70,    0,   62,    0,    0,

       62,    0,   70,    0,    0,   70,   71,   71,   71,   71,
       72,   72,   72,   72,    0,   62,    0,   62,   74,   74,
       74,   74,   75,   75,   75,   75,    0,    0,   75,   70,
        0,    0,   70,  119,   74,  119,  119,  119,   71,  160,
      160,  160,   72,   77,   77,   77,   77,   70,    0,   70,
       74,  164,  164,  164,   75,   75,   76,   76,   76,   76,
       74,    0,   78,   78,   78,   78,    0,   77,    0,   80,
       80,   80,   80,   76,   76,   77,    0,    0,    0,   81,
       81,   81,   81,   82,   82,   82,   82,  120,   76,  120,
      120,  120,   82,   77,   78,   83,   83,   83,   83,   76,

       76,   80,   81,    0,    0,   84,   84,   84,   84,    0,
        0,   81,    0,   83,  161,   82,  161,  161,  161,   82,
       85,   85,   85,   85,    0,    0,    0,   83,   81,   84,
       86,   86,   86,   86,    0,    0,    0,   84,    0,   83,
       87,   87,   87,   87,   88,   88,   88,   88,   95,   95,
       95,   95,   85,    0,   86,   84,   88,    0,   87,    0,
        0,    0,   86,   89,   89,   89,   89,    0,    0,   89,
        0,    0,   87,    0,    0,    0,   88,    0,    0,    0,
       86,    0,    0,   88,   87,    0,    0,   89,   90,   90,
       90,   90,    0,    0,    0,   89,   89,   91,   91,   91,

       91,    0,    0,    0,   91,    0,    0,   90,   92,   92,
       92,   92,    0,   89,   93,   93,   93,   93,   92,    0,
       90,   94,   94,   94,   94,    0,    0,    0,   93,   91,
        0,   91,    0,   90,  113,  113,  113,  113,    0,  126,
       92,  126,  126,  126,  126,   92,   93,  127,  127,  127,
      127,    0,    0,   94,    0,   93,  128,  128,  128,  128,
      131,  131,  131,  131,  132,  132,  132,  132,    0,    0,
        0,  134,  134,  134,  134,    0,  131,    0,    0,  127,
        0,  133,  133,  133,  133,    0,  132,    0,  128,    0,
        0,    0,  131,    0,    0,  134,  132,    0,  133,    0,

        0,  133,  131,  134,  135,  135,  135,  135,    0,    0,
      135,    0,  132,  133,    0,  136,  136,  136,  136,    0,
        0,  134,    0,    0,  133,  136,    0,  133,    0,  137,
      137,  137,  137,    0,    0,    0,  135,  135,  137,  139,
      139,  139,  139,  137,    0,    0,    0,  136,  138,  138,
      138,  138,  136,    0,    0,    0,  138,    0,  139,    0,
        0,  137,    0,    0,    0,  137,  140,  140,  140,  140,
      137,  139,    0,    0,    0,    0,  140,    0,    0,    0,
      138,    0,    0,  138,  139,  141,  141,  141,  141,    0,
      142,  142,  142,  142,    0,    0,    0,  141,  140,    0,

        0,    0,    0,  140,  142,  143,  143,  143,  143,    0,
      144,  144,  144,  144,  143,    0,    0,  141,    0,    0,
        0,  143,  142,    0,  141,  145,  145,  145,  145,    0,
        0,  142,    0,    0,    0,  144,    0,  143,    0,    0,
        0,  143,  144,    0,    0,  145,    0,  143,  146,  146,
      146,  146,  148,  148,  148,  148,    0,  145,    0,    0,
        0,  144,    0,  147,  147,  147,  147,    0,    0,    0,
      146,  145,  149,  149,  149,  149,  148,    0,    0,    0,
      146,  147,    0,    0,  148,  150,  150,  150,  150,  167,
      167,  167,  167,    0,    0,  147,  146,  168,  168,  168,

      168,    0,  148,  168,  149,    0,    0,  147,  169,  169,
      169,  169,  170,  170,  170,  170,    0,  150,    0,    0,
        0,  167,    0,  171,  171,  171,  171,  169,  170,  168,
      168,  172,  172,  172,  172,    0,    0,  171,    0,    0,
      169,    0,    0,    0,  170,  173,  173,  173,  173,  174,
      174,  174,  174,  169,  170,  171,    0,    0,  175,  175,
      175,  175,    0,  172,  171,    0,    0,    0,  174,  175,
        0,  176,  176,  176,  176,    0,    0,  173,    0,    0,
        0,  174,  177,  177,  177,  177,  178,  178,  178,  178,
      175,    0,    0,    0,  174,  176,  175,    0,  178,  179,

      179,  179,  179,  176,  180,  180,  180,  180,  181,  181,
      181,  181,  180,    0,  177,    0,    0,    0,  178,    0,
        0,  176,    0,  179,    0,  178,  182,  182,  182,  182,
        0,  179,  183,  183,  183,  183,  180,    0,    0,  180,
      181,  184,  184,  184,  184,  186,  186,  186,  186,  179,
      185,  185,  185,  185,  183,    0,    0,    0,  182,    0,
      187,  187,  187,  187,  183,    0,    0,    0,    0,  185,
      187,    0,    0,  184,    0,    0,    0,  186,    0,    0,
      183,    0,  185,  188,  188,  188,  188,  189,  189,  189,
      189,    0,  187,    0,    0,  185,    0,  187,  194,  194,

      194,  194,  195,  195,  195,  195,  194,  196,  196,  196,
      196,  197,  197,  197,  197,  188,    0,  196,    0,  189,
      195,  198,  198,  198,  198,  199,  199,  199,  199,  197,
      194,    0,    0,  194,  195,  200,  200,  200,  200,  196,
        0,    0,    0,  197,  196,    0,  195,    0,    0,  200,
        0,    0,    0,  198,    0,  197,    0,  199,  201,  201,
      201,  201,  202,  202,  202,  202,    0,  200,  201,    0,
        0,  203,  203,  203,  203,  202,  200,  203,  204,  204,
      204,  204,  205,  205,  205,  205,  206,  206,  206,  206,
      201,    0,    0,    0,  202,  201,  204,  209,  209,  209,

      209,    0,  202,  203,  203,    0,    0,  205,    0,    0,
      204,    0,    0,    0,  205,    0,    0,    0,  206,    0,
        0,  209,  204,  210,  210,  210,  210,    0,    0,  209,
        0,    0,    0,  205,  211,  211,  211,  211,  212,  212,
      212,  212,  214,  214,  214,  214,    0,  209,  213,  213,
      213,  213,    0,    0,    0,  210,  215,  215,  215,  215,
        0,    0,  211,  212,  214,    0,  211,  213,    0,    0,
      212,    0,    0,    0,  214,  216,  216,  216,  216,    0,
      213,  217,  217,  217,  217,    0,    0,  211,  215,  212,
      214,  216,    0,  213,  218,  218,  218,  218,  219,  219,

      219,  219,  220,  220,  220,  220,    0,  216,  219,  221,
      221,  221,  221,  217,    0,    0,    0,  216,  218,  221,
      222,  222,  222,  222,    0,    0,  218,    0,    0,    0,
      219,    0,    0,    0,  220,  219,    0,    0,  222,    0,
        0,  221,    0,    0,  218,    0,  221,  223,  223,  223,
      223,    0,  222,  224,  224,  224,  224,  225,  225,  225,
      225,    0,    0,    0,  222,  226,  226,  226,  226,    0,
        0,  225,  227,  227,  227,  227,    0,    0,    0,  223,
      228,  228,  228,  228,    0,  224,    0,  226,    0,  225,
      229,  229,  229,  229,    0,    0,    0,  226,  225,  230,

      230,  230,  230,    0,  227,    0,    0,    0,  229,    0,
        0,    0,  228,  226,  231,  231,  231,  231,  232,  232,
      232,  232,  229,    0,  231,    0,    0,    0,    0,    0,
        0,  230,    0,    0,  229,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  231,    0,    0,    0,
      232,  231,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  237,  237,  237,  237,  237,  237,  238,  238,  238,
      238,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  240,    0,    0,    0,  240,    0,  240,  241,  241,
      241,  241,  242,  242,  242,  242,  243,  243,  243,  243,
      243,  243,  244,  244,  244,  244,  245,  245,  245,  245,
      245,  245,  246,  246,  246,  247,  247,  247,  247,  248,
      248,  248,  248,  248,  248,  249,  249,  249,  249,  249,
      249,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,

      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[58] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 3 "lexer.l"

    //#include "tokens.h"
    #include <stdio.h>
    #include <stdlib.h> 
    #include "syntax.tab.h"

    
    char str_buf[256];
    int error_counter = 0;
    void tokenPrint(int token_id);
    void yyerror(const char* err);
    int strToInt(char *str);
    int length ;
    int count = 0;
    

#line 926 "lex.yy.c"
/* Read only 1 File */
/* Case insensitive tokens (e.x ClaSS == class) */
/* count lines */

/* Ισοδυναμιες Κλασεων */
#line 932 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define SINGLE_LINE_COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 44 "lexer.l"


#line 1154 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 234 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1552 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "lexer.l"
{tokenPrint(T_FUNCTION); return T_FUNCTION; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "lexer.l"
{tokenPrint(T_SUBROUTINE); return T_SUBROUTINE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "lexer.l"
{tokenPrint(T_END); return T_END; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "lexer.l"
{tokenPrint(T_COMMON); return T_COMMON; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "lexer.l"
{tokenPrint(T_INTEGER); return T_INTEGER; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "lexer.l"
{tokenPrint(T_REAL); return T_REAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "lexer.l"
{tokenPrint(T_COMPLEX); return T_COMPLEX; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 53 "lexer.l"
{tokenPrint(T_LOGICAL); return T_LOGICAL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 54 "lexer.l"
{tokenPrint(T_CHARACTER); return T_CHARACTER; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 55 "lexer.l"
{tokenPrint(T_DATA); return T_DATA; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 56 "lexer.l"
{tokenPrint(T_CONTINUE); return T_CONTINUE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 57 "lexer.l"
{tokenPrint(T_GOTO); return T_GOTO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 58 "lexer.l"
{tokenPrint(T_CALL); return T_CALL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 59 "lexer.l"
{tokenPrint(T_READ); return T_READ; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 60 "lexer.l"
{tokenPrint(T_WRITE); return T_WRITE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 61 "lexer.l"
{tokenPrint(T_IF); return T_IF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 62 "lexer.l"
{tokenPrint(T_THEN); return T_THEN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 63 "lexer.l"
{tokenPrint(T_ELSE); return T_ELSE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 64 "lexer.l"
{tokenPrint(T_ENDIF); return T_ENDIF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 65 "lexer.l"
{tokenPrint(T_DO); return T_DO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 66 "lexer.l"
{tokenPrint(T_ENDDO); return T_ENDDO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 67 "lexer.l"
{tokenPrint(T_STOP); return T_STOP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 68 "lexer.l"
{tokenPrint(T_RETURN); return T_RETURN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 69 "lexer.l"
{tokenPrint(T_LENGTH); return T_LENGTH; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 71 "lexer.l"
{tokenPrint(T_ID); yylval.strval = strdup(yytext); return T_ID; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 73 "lexer.l"
{tokenPrint(T_ICONST); yylval.intval = strToInt(yytext); return T_ICONST;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 75 "lexer.l"
{tokenPrint(T_RCONST); yylval.realval = atof(yytext); return T_RCONST;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 77 "lexer.l"
{tokenPrint(T_LCONST); yylval.booleanval = strdup(yytext); return T_LCONST;}                                            
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "lexer.l"
{tokenPrint(T_CCONST); yylval.charval = yytext[1]; return T_CCONST; } 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "lexer.l"
{tokenPrint(T_OROP); return T_OROP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "lexer.l"
{tokenPrint(T_ANDOP); return T_ANDOP;}                
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "lexer.l"
{tokenPrint(T_NOTOP); return T_NOTOP;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "lexer.l"
{tokenPrint(T_RELOP); return T_RELOP;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "lexer.l"
{tokenPrint(T_ADDOP); return T_ADDOP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "lexer.l"
{tokenPrint(T_ADDOP); return T_ADDOP;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "lexer.l"
{tokenPrint(T_MULOP); return T_MULOP;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "lexer.l"
{tokenPrint(T_DIVOP); return T_DIVOP;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 91 "lexer.l"
{tokenPrint(T_POWEROP); return T_POWEROP;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 96 "lexer.l"
{tokenPrint(T_LPAREN); return T_LPAREN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 97 "lexer.l"
{tokenPrint(T_RPAREN); return T_RPAREN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 98 "lexer.l"
{tokenPrint(T_COMMA); return T_COMMA; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 99 "lexer.l"
{tokenPrint(T_ASSIGN); return T_ASSIGN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 100 "lexer.l"
{tokenPrint(T_LBRACK); return T_LBRACK; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 101 "lexer.l"
{tokenPrint(T_RBRACK); return T_RBRACK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 102 "lexer.l"
{tokenPrint(T_COLON); return T_COLON; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "lexer.l"
{
    
    strcpy(str_buf, "");
    BEGIN(STRING);
    length = atoi(yytext); // Αποθήκευση του μήκους συμβολοσειράς
    count = 0; 
    printf("Μήκος συμβολοσειράς: %d\n", length);
     if (length == 0){
        BEGIN(INITIAL);
        printf("%d\n", length);
    }
   
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 119 "lexer.l"
{
    strcat(str_buf, yytext); // Προσθήκη του κειμένου στο str_buf
    count += strlen(yytext); // Ενημέρωση του μετρητή χαρακτήρων
    //printf("%s\n", str_buf); // Εκτύπωση της συμβολοσειράς
   
    if(count >= length) { // Ελέγχουμε αν έχουμε φτάσει στο τέλος της συμβολοσειράς
        //printf("%s\n", str_buf); // Εκτύπωση της συμβολοσειράς
        BEGIN(INITIAL); // Επιστροφή στην αρχική κατάσταση
        printf("%s\n", str_buf); // Εκτύπωση της συμβολοσειράς
        yylval.strval = strdup(str_buf);
        //strcat( T_STRING , str_buf);
        return T_STRING;    
    }
}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 134 "lexer.l"
{ }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 139 "lexer.l"
{
        if(strlen(yytext) == 2 ){
            if(strcmp(yytext, "\\n") == 0) {
                count++;
                strcat(str_buf, "\n");
            }else if (strcmp(yytext, "\\t") == 0) {
                count++;
                strcat(str_buf, "\t");
            }else if (strcmp(yytext, "\\f") == 0) {
                count++;
                strcat(str_buf, "\f");
            }else if (strcmp(yytext, "\\r") ==0) {
                count++;
                strcat(str_buf, "\r");
            }else if (strcmp(yytext, "\\b") == 0) {
                count++;
                strcat(str_buf, "\b");
                count++;
            }else {
                strcat(str_buf, &yytext[1]);
                count++;
            }
        } else {
            strcat(str_buf, yytext);
            
        }
        
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 170 "lexer.l"
{ yyerror("End of string without closing it\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 172 "lexer.l"
{ BEGIN(SINGLE_LINE_COMMENT); }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 173 "lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 174 "lexer.l"
{ }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 178 "lexer.l"
{  } /* kenoi xarakthres */
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 179 "lexer.l"
{  } /* new line for linux */
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 180 "lexer.l"
{  } /* new line for windows */
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLE_LINE_COMMENT):
#line 182 "lexer.l"
{return T_EOF; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 184 "lexer.l"
{yyerror("Unrecognized character !\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 189 "lexer.l"
ECHO;
	YY_BREAK
#line 1572 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 234 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 234 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 233);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 189 "lexer.l"


void tokenPrint (int token_id){
    //printf("Found token '%s' (%d) at line %d\n", yytext,token_id, yylineno);
    //printf("Found token (%s) \n", yytext);
    //yytext deixnei thn parousa anagnvrismenh le3i

    if(token_id == T_ICONST) {
       // printf("[LINE %d] INTEGER TOKEN \'%s\' . Base 10: %d\n", yylineno, yytext,  strToInt(yytext) );
    }else if(token_id == T_RCONST) {
        //printf("[LINE %d] REAL TOKEN \'%s\' . Base 10: %d\n", yylineno, yytext,  strToInt(yytext) );
    }else {
        //printf("[LINE %d]  TOKEN \'%s' (%d)\n", yylineno, yytext, token_id );
    }
}


int strToInt(char *str) {

    if(strncmp(str, "0o", 2) == 0|strncmp(str, "0O", 2) == 0) {//8diko arithmo
        return (int) strtoll(&str[2], NULL, 8);
    }else if (strncmp(str, "0B", 2) == 0|strncmp(str, "0b", 2) == 0) {//2diko arithmo
        return (int) strtoll(&str[2], NULL, 2);
    }else if (strncmp(str, "0X", 2) == 0|strncmp(str, "0x", 2) == 0) {//16diko arithmo
        return (int) strtoll(&str[2], NULL, 16);
    }else  {
        return (int) strtoll(str, NULL, 10);
    }
}

int strTofloat(char *str) {

    if(strncmp(str, "0o", 2) == 0|strncmp(str, "0O", 2) == 0) {//8diko arithmo
        return (float) strtoll(&str[2], NULL, 8);
    }else if (strncmp(str, "0B", 2) == 0|strncmp(str, "0b", 2) == 0) {//2diko arithmo
        return (float) strtoll(&str[2], NULL, 2);
    }else if (strncmp(str, "0X", 2) == 0|strncmp(str, "0x", 2) == 0) {//16diko arithmo
        return (float) strtoll(&str[2], NULL, 16);
    }else  {
        return (float) strtoll(str, NULL, 10);
    }
}

void yyerror(const char* err) {
    error_counter++;
    printf("[ERROR - LINE %d] %s\n", yylineno, err);

    if(error_counter ==5) {
        printf("maximoum errors found\n");
        exit(EXIT_FAILURE);
    }

    yyless(1);
}

